### PR TITLE
Add a 100 ms timeout to the call to pulseIn. 

### PR DESCRIPTION
**Pull request by RBerliner**
The project will hang in a Security Token loop if the timeout is not present

### CODE REVIEW

**Comment by RBerliner** [comment]
Something is wrong with this code. I will need to resubmit the request aqfter I figure out what it is

**Comment by ba58smith** [comment]
I didn't look very closely, but I think you need to use an `unsigned long` to work with `micros()`.

**Comment by RBerliner** [comment]
You are right - but my misunderstanding was more general. The delay in pulseIn is to be in microsec - not millisec. The code works with 50000 as the delay.

I have another problem - the pulseIn and notify statements in the original code have been replaced with 

this->emit(pulseIn(input_pin, HIGH));

I am trying to find where this function is documented and if it supports a timeout.

**Comment by RBerliner** [comment]
It appears I am making too much out of it - I can probably just use the timeout in the emit(pulseIn...) but I need to point things to the head of SignalK/SensESP for testing. My platformio.ini is currently pointed to SignalK/Sensesp

**Pull request closed without merging**
