### PR TITLE
Fix compiler warning in Integrator

### PR DESCRIPTION
**Pull request by ba58smith**
Solves the compiler warning in Issue #316.

### CODE REVIEW

**Review by joelkoz — APPROVED** [review]
I THINK I follow this. ;)

Looks good.

**Comment by ba58smith** [comment]
It's weird that it throws a compiler warning. In one case - a PR that someone else was working on - I think a simple change in the order of the member varibles - was the difference between it compiling and not!

Merging.

**Comment by joelkoz** [comment]
If you look at our `platformio.ini`, we have this line:
```
build_unflags = -Werror=reorder
```

The "-Werror=reorder" means "turn the reorder warning into an error", but since its in the `build_unflags" section, that means "remove it from the build flags set."

If a user creates their own `platformio.ini` file and doesn't put that line in it, their version will not compile, as I think the default for this option is to consider this an error.

**Comment by ba58smith** [comment]
Makes sense, but I never understood that `-Werror=reorder` until you just explained it. Good to know, as it'll surely come up again with another end user.

**Pull request merged**
