### PR TITLE
Fix deprecated build flag for configuring flash

### PR DESCRIPTION
**Pull request by ba58smith**
Addresses Issue #278 .

Fixed the same way as it was fixed in the example platformio.ini file: PR #228 .

### CODE REVIEW

**Review by joelkoz — COMMENTED** [review]
I see this makes this consistent with the `examples/platformio.ini`, which is a good thing.  But, this failed to build?  Did this break the build somehow?

Also - just for my own knowledge, is this entry even necessary?  I am able to build SensESP without any kind of error.  Of course, I've never tried to deploy it, but you aren't supposed to deploy the library directly. What does this even do? I saw this come up when helping a user, but he was incorrectly using this `platformio.ini` to deploy his app.

**Comment by joelkoz** [comment]
Error from the CI logs.  Not sure if the "failure" is a big deal or not:

```
Environment     Status    Duration
--------------  --------  ------------
d1_mini         SUCCESS   00:01:55.596
esp32dev        SUCCESS   00:01:56.763
esp-wrover-kit  FAILED    00:00:07.529
==================== 1 failed, 2 succeeded in 00:03:59.888 ====================
Error: Process completed with exit code 1.
```

**Comment by ba58smith** [comment]
The old build flag (-Wl,-Teagle.flash.4m1m.ld) has been in the SensESP `platformio.ini` since the very beginning. I think it's necessary because the default uses 512k instead of 1 meg for whatever the second parameter is, and I'm guessing @mairas determined that 1 meg was needed?
It's always worked, and this is just the new way of doing it, so I'm not going to change it.

**Comment by ba58smith** [comment]
I have no idea why it would have failed the CI check for the esp-rover-kit, as that's an ESP32. I think we can safely ignore the failure. (I had another PR fail the CI check, and the ONLY change in it was a change to a comment.)

**Comment by mairas** [comment]
Right, this was the change you requested me to do for the CI ini file. I hadn't actually looked into this PR earlier (because of the red X next to it).

**Comment by mairas** [comment]
Passed on a retry. Merging.

**Pull request merged**
