### PR TITLE
Add VoltageDividerR1 class 

### PR DESCRIPTION
**Pull request by RBerliner**
Added the VoltageDividerR1 class and placed VoltageDividerR1 and VoltageDividerR2 in the same file voltageDivider.cpp
Updated the temperature_sender example to use the new voltagedividerf.h file and the Builder class.

I hope that I have got a clean PR this time without unrelated commits. Please advise.

### CODE REVIEW

**Comment by RBerliner** [comment]
I don't know why the commits from Airas show up but they do. I did

git pull upstream master -- rebase

in my local repo followed by a push to my github repo which was rejected - I had to do 

git pull --rebase 

before it would let me push

**Comment by ba58smith** [comment]
@RBerliner - when you start making your pull request, do you start by creating a new branch just for the commits in this new PR?

`git checkout -b newBranchName`

I don't see any branches in your Fork other than "master", which is why I'm asking.

**Comment by RBerliner** [comment]
No, I did not do that.

I deleted my github repo, forked the SensESP repo then cloned it to my local machine. I added in the VoltageDivider modifications, committed and pushed. I added SignalK/SensESP as the upstream remote. In the meantime Airas had made a commit so I did a git pull upstream master --rebase which appeared to me to work. I then tried to push again to my repo on github but it would not let me - I had to do another git pull origin --rebase.

Then I could push and make the PR.

**Comment by RBerliner** [comment]
ARe you supposed to make a new branch just for the PR? I can certainly do so in future.

**Comment by ba58smith** [comment]
@RBerliner - When I first started using git, I found a really excellent beginner's guide to contributing to a git project, and that's where I learned about that - adding a new branch for every new PR. I don't know how much that has to do with the (usual) success of my process, but I always do it.

**Comment by ba58smith** [comment]
@RBerliner - with all the recent info in the Slack thread about using git properly, do you want to try this again? This time, though, be sure to make a separate branch just for your PR.

**Comment by RBerliner** [comment]
It was on my list of things to do today. I will attempt to close this PR at my end. If that fails, will you please close it at your end - I want to start a fresh PR

**Pull request closed without merging**
