### PR TITLE
add support for ESP32

### PR DESCRIPTION
**Pull request by loopsmark**
Added support to the esp32 platform and the board az-delivery-devkit-v4

### CODE REVIEW

**Comment by ba58smith** [comment]
Looks good to me, but I'm not the expert. @mairas needs to review this before it can be merged. I have just two questions:
1. Have you tested this thoroughly with an ESP8266 yet? If so, which module? 

2. You've made it work with a specific ESP32 board (az-delivery-devkit-v4). Have you tested it with any other ESP32 boards? Which ones?

**Comment by loopsmark** [comment]
1. Nope, I do not have any ESP8266 to test it with. Definitely someone should check if this merge is braking something.
2. That is the only board I have right now. I have another board coming this week, so I could test it in the other one

**Comment by ba58smith** [comment]
> 1. Nope, I do not have any ESP8266 to test it with. Definitely someone should check if this merge is braking something.
> 2. That is the only board I have right now. I have another board coming this week, so I could test it in the other one

OK, I will need to get my system ready to test this, and ready to roll back if it breaks something. I have the Wemos D1 Mini ESP8266, and at least one ESP32 that's different from the one you have. I will try them both. Thanks for the work!

**Comment by ba58smith** [comment]
I have several other things in the works right now (with SensESP, and with my boat), so it will be a while before I can test this. Probably at least two weeks. But I will get to it sooner if I can.

**Comment by ba58smith** [comment]
@loopsmark , I ended up testing this today on the Wemos D1 mini, the ESP8266 that I've always used. It's working on all four of my Wemos's, sending live data to my SK Server. I still want to try it on some ESP32's that I have, and I hope @mairas will be able to test this on his ESP's, too.

**Comment by loopsmark** [comment]
@ba58smith , after more testing I realized it's not working perfectly for the ESP32. It compiles and put the ESP32 in that mode where you can join its network, but once you put the network credentials where the SignalK server is running fails in the mDNS and goes into a boot loop. By hardcoding the IP and port of the server it works though

**Comment by ba58smith** [comment]
> @ba58smith , after more testing I realized it's not working perfectly for the ESP32. It compiles and put the ESP32 in that mode where you can join its network, but once you put the network credentials where the SignalK server is running fails in the mDNS and goes into a boot loop. By hardcoding the IP and port of the server it works though

OK, I will wait until you find and fix that, and commit it here, before I do any ESP32 testing.

**Comment by loopsmark** [comment]
@ba58smith looks like this is related to the ReactESP and/or WebSockets. This is not gonna be an easy fix and probably beyond this repo. I'll investigate anyway

**Comment by ba58smith** [comment]
@loopsmark - you seem to understand very well the way libraries are managed in PlatformIO. (I say that based on the changes you made to platformio.ini for this PR.) I don't, so I hope you can help me. I've written the interface to several new sensors lately (ADS1015/1115, BME280, INA219, etc.), and of course, each one requires its own library. I initially added them to the platformio.ini that's in my SensESPTest project folder, simply by copying/pasting the name of the library into the `lib_deps` section under `[env:d1_mini]`. It works, but after doing that with a few new libraries, I realized that they should really be in the platformio.ini that belongs to the SensESP project - the one you made all the modificaitons to. So I added all the library names there, and deleted them all from my Project's platformio.ini - but it won't compile. I know libraries can be installed at the Project level or the Global level, but nothing I have tried with changing those has mattered - I still have to have all of the libraries for new sensors in my SensESPTest's platformio.ini. I've Googled and read everything I can find about this, but nothing is very clear. Can you help? You can email me at ba58smith at gmail, and then I'll delete this from here, as it clearly doesn't belong here. Thanks!

**Comment by ba58smith** [comment]
@loopsmark - If the problem is with ReactESP, notice that that's a project @mairas, who also started this project. If you need a change to it, I'm sure he'll do it.

**Comment by loopsmark** [comment]
@ba58smith Ok, after rebase with master now it's working as expected (don't ask me why), i.e. no more problems with mDNS. Anyways someone should test this in another ESP32

**Comment by ba58smith** [comment]
> @ba58smith Ok, after rebase with master now it's working as expected (don't ask me why), i.e. no more problems with mDNS. Anyways someone should test this in another ESP32

Cool! I have at least one ESP32, maybe two. I can test for running and sending "standard sensor" data to SK (systemHz, uptime, etc.), and maybe I can hook up an actual sensor or two.

**Comment by gzahl** [comment]
Hi, i have also worked on porting to ESP32. (Started before you pushed your work.)
I think our result is very similar. I have still put up a pull request so everybody can look at the differences ( https://github.com/SignalK/SensESP/pull/118 )
Especially i have used only a single EspTrueRandom library and made SensESP usable as a project dependency without having to state any other dependencies explicitly. Maybe these things could be split into two PR as well.

**Comment by loopsmark** [comment]
It seems the PR #118 will get merged, I'll close this one

**Comment by ba58smith** [comment]
@loopsmark - Would you please do a new PR for your platformio.ini? I really like the way you set that up for different boards.
Thanks for this PR (support for ESP32). I was just trying to resolve all the differences between yours and the other one, to the point that they would have been identical. If there's anything about the other one that you would do differently, I would like to know, and to understand your objection. Please do that in a comment on that PR, if you have any.

**Comment by loopsmark** [comment]
@ba58smith sure, but I will change more things that just the .ino to make the repo a bit cleaner. To avoid merge conflicts I'll wait till the #118 is merged to implement it.

**Pull request closed without merging**
