### PR TITLE
Sample platformio.ini

### PR DESCRIPTION
**Pull request by mairas**
Provide a sample `platformio.ini` file in `examples`. Also reformat and standardize variable naming for all examples.

### CODE REVIEW

**Comment by JohnySeven** [comment]
@mairas maybe it would be nice to have complete copy&paste example as kick start? Add mention in the getting started for downloading .zip file with simple example - maybe just sending default sensors?

**Comment by grahamkendall82** [comment]
@mairas..I appreciate this greatly. I was suffering from information overload on what to do with the libraries but it all makes sense now. Thank you

**Comment by mairas** [comment]
> @mairas maybe it would be nice to have complete copy&paste example as kick start? Add mention in the getting started for downloading .zip file with simple example - maybe just sending default sensors?

That's a good idea! Maybe you can make a PR? :-)

**Comment by mairas** [comment]
Merging.

**Pull request merged**
