### PR TITLE
Update FX8700 example

### PR DESCRIPTION
**Pull request by tedenda**
This is the updated example with correct SK paths and also have Attitude in place.

This PR can only be merged when #216 is done and this example is verified to work as expected.

### CODE REVIEW

**Comment by DanielG86** [comment]
Great.
I know whether the attitude approach works, hopefully you do. 
In line 44 the sk path shows “navigation/headingCompass”, where I believe the / should be a dot.
Furthermore, you could argue to make this headingMagnetic, since after calibration on the boat, the sensor should give magnetic heading data.

**Comment by tedenda** [comment]
@DanielG86 Thanks, updated!
Regarding the headingMagnetic, you are probably right, changed to that for now.

**Comment by BjarneBitscrambler** [comment]
@tedenda - The Sensor Fusion v7 library is working and I have started porting the SensESP Orientation example over to use this library. Would you like me to review your changes proposed in this PR and merge them into the revised Orientation example? That would allow us to retire this PR once SensESP is switched over to the new library.

**Comment by tedenda** [comment]
Yes, that sounds like a good idea.

When you add your PR you just mention this PR with `Close #225` GitHub will pick that up and do that while merging your PR.

**Comment by BjarneBitscrambler** [comment]
I now have a working example that uses the correct paths for *Attitude* and *headingCompass*. It's submitted as PR#349 if you could have a look... Thanks!

**Comment by mairas** [comment]
This PR seems to have gone stale; closing.

**Pull request closed without merging**
