### PR TITLE
WIP: GitHub Pages site skeleton

### PR DESCRIPTION
**Pull request by mairas**
This is a skeleton for GitHub Pages documentation site. I have mostly concerned myself with the basic scaffolding; how to get the site rendered; navigation links and such. A rudimentary structure for content has been sketched out, but that (like everything else) is quite tentative and subject for improvement!

I haven't yet shoveled existing documentation in place or written any planned content. Also, some things are still missing such as proper integration with the Doxygen documentation.

README has some very rudimentary documentation on how to render and serve the site locally.

### CODE REVIEW

**Comment by mairas** [comment]
This is what the site home page looks like at the moment:

Screenshot 2021-12-06 at 20 40 54

**Comment by ba58smith** [comment]
You've requested my review, but what would you like me to review? It LOOKS really cool, but beyond that, it sounds like there's not yet much of the final content you have in mind, correct?

**Comment by mairas** [comment]
> You've requested my review, but what would you like me to review? It LOOKS really cool, but beyond that, it sounds like there's not yet much of the final content you have in mind, correct?

Given that you have been essential in documenting SensESP so far, I'd be quite interested in your opinions on the overall approach, usability (both for content creator and user), navigation etc.

**Comment by ba58smith** [comment]
Are you going to "port" (more like copy-paste) all of the existing documentation (the README and the Wiki) into this new format as part of the initial steps of creating the GH Pages? I hope so - there's a lot of good content there, and even though version 2.0 is going to have some significant differences, much of it is still relevant. If you'll do that, then you and I can coordinate on how that existing content is edited to fit the new format (some by you, some by me, all by me, whatever), and how it's edited to reflect all the V2.0 changes. If you'd rather I do that (port the existing content into the new format), let me know. It just doesn't make sense for both of us to have our fingers in that pie.

**Comment by mairas** [comment]
As discussed offline, the intention never was to not reuse the Wiki material. The contents have now been shoveled to the GitHub Pages structure but not yet modified in any way. I'll merge this PR - further PRs can be made to organize and improve the content.

**Pull request merged**
