### PR TITLE
ValueProducer::emit(value)

### PR DESCRIPTION
**Pull request by mairas**
Most sensors keep repeating the following pattern:

    output = some_value;
    notify();

This PR implements `ValueProducer::emit(value)` that changes the pattern to the following:

    this->emit(some_value);

### CODE REVIEW

**Comment by JohnySeven** [comment]
Looking very nice! 👍

**Comment by ba58smith** [comment]
Was this done simply to reduce two lines of code to one? (In a whole bunch of places, of course.) I'm not questioning it - just want to make sure I understand exactly what this PR does.

**Comment by mairas** [comment]
Yes, pretty much so. And also to reduce the usage of an explicit output variable, which I think is a bit of an anti-pattern in our `ValueProducer` class implementations.

**Comment by mairas** [comment]
Merging.

**Pull request merged**
