### PR TITLE
Mass renaming of classes, methods and variables

### PR DESCRIPTION
**Pull request by mairas**
This is something I'd like to get in before the next release.

I've gone through the codebase and attempted to rename classes, methods and variables to follow the naming convention. In the interested of backwards-compatibility, I've provided deprecated typedefs or duplicated methods whenever a major API has changed. However, in a few cases I've decided a filename of some particular sensor or transform should be renamed. For those, the changes are backwards-incompatible.

I've tested the changes by trying to build each example file and they seem to be fine. However, the PR is pretty massive, so stuff might accidentally break.

Each change has been isolated in a commit of its own, so reviewing commit per commit might be easier than going through the changed files.

### CODE REVIEW

**Comment by JohnySeven** [comment]
Wov, that's quite breaking change. I think many ppl will not be happy about that. Have you think about making the master obsolete branch and go forward with primary as suggested by github? So that everyone can keep using their code, but if they want new shiny stuff they can by just switching to primary branch as to keep going with new features.

**Comment by mairas** [comment]
The PR isn't breaking that much. The only intentional breakages are some filename renamings: `max31856TC_input.*` to `max31856_thermocouple` and `ultrasonic_input.*` to `ultrasonic_distance.*`. They're relatively recently implemented sensors and likely not to be very widely used yet.

I've attempted to provide typedefs for all renamed classes and forwarding functions for any renamed functions.

As for renaming master branch to main, I'm in favor of doing that, but I don't think there should be an underlying functional change. But GitHub recommends people to wait until they have their tooling ready: https://github.com/github/renaming#later-this-year

**Comment by ba58smith** [comment]
Man, you must have been really bored! :-) :-)

Although some of those changes will break things, my experience with my own SensESP projects (when *I* have made a breaking change) is that VS Code does a great job of identifying the problem, and it usually takes only a few minutes to resolve all of them. I'm OK with it.

For future reference, @mairas - where are the naming conventions spelled out? I want to adhere to them in the future, and it will help me help others get their PR's right before merging.

**Comment by mairas** [comment]
> Man, you must have been really bored! :-) :-)

Well, yeah, it was a chore, but VSCode has become quite good in providing refactoring assistance such as renaming symbols in C++. And I thought it really should be done before we approach 1.0. :-)
 
> For future reference, @mairas - where are the naming conventions spelled out? I want to adhere to them in the future, and it will help me help others get their PR's right before merging.

It's this one: https://google.github.io/styleguide/cppguide.html

I added that and quite a bit of other guidance in the wiki but you must've missed my post about that on Slack.

Anyway, I'll add some contribution guidance in the README.md as well. It kinda fits the theme of this PR so I'll just slap it on...

**Pull request merged**
