### PR TITLE
Unique SSID for each ESP

### PR DESCRIPTION
**Pull request by ba58smith**
See Issue #86.

### CODE REVIEW

**Comment by ba58smith** [comment]
DO NOT MERGE THIS YET. Although it does what I intended it to do, there appears to be a bug way down deep in Wifi Manager that doesn't erase the SSID and pw of the configuration UI when `resetSettings()` is called. If it's not erasing those, then it's probably also not erasing any custom parameters, which is what this PR is all about. https://github.com/tzapu/WiFiManager/issues/142

**Comment by mairas** [comment]
Looks good to me!

**Comment by ba58smith** [comment]
Matti,

It works, but there's still something not quite right about it. Sometimes,
when the ESP8266 is connected to the SK server and sending data, it's still
broadcasting the configuration SSID. For example, right now, in my list of
available wifi networks, I see "Configure MEtemps". MEtemps is the name of
one of my ESP8266's. I expect to see that SSID in my list of available
networks ONLY when the ESP can't connect to my boat's wifi, and it starts
up the AP mode so that the initial configuration can be done (of wifi SSID
and password, and the custom hostname for the Device). When I connect to
that SSID, and go to 192.168.4.1, I get the configuration UI that you and
JKoz wrote (where you configure the sensors and transports), not the config
UI for setting up the wifi and custom hostname. I hope that makes sense.

I'm wondering if somehow the mode in WifiManager is not being set
correctly, but I can't figure it out. Do you remember how this works well
enough to have any thoughts on it? If so, I'd love to hear them. Otherwise,
I think I'll start digging into the different WifiManager modes, and see if
this has something to do with the wrong mode being active.

Thanks,

@butch

Brian "Butch" Smith
M/V Smartini
www.smartini.life

**Comment by ba58smith** [comment]
OK, this PR works. Each of my four ESP's is now broadcasting a custom SSID when my onboard wifi is turned off (the wife that all four of the ESP's are supposed to connect to). 
If you ever have what appears to be an outdated SSID being broadcast for a particular ESP, try the PlatformIO option "Erase Flash", and then upload the new firmware.
Issue #87 is still open, and is made even more obvious by this PR, as you'll now see a separate SSID being broadcast by all of your ESP's any time your wifi is not available.

**Pull request merged**
